### ISSUE TITLE
Required documentation

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ethermint#307]
Some things that need to be documented (in no specific order):

- [x] Business logic features: fast-finality, PoS, smart contracts in Solidity, SDK features, IBC and Web3 compatible, etc.
- [x] Run a node
- [x] Setting up a validator
- [x] Launching a local or public testnet
- [x] Upgrade and export procedure
- [x] Hard-spoon docs
- [x] Ethemint's staking denomination: Photon. Economic model, link to @sunnya97's [paper](https://github.com/cosmos/cosmos/blob/master/Cosmos_Token_Model.pdf). [Reference](https://medium.com/tendermint/proposed-cosmos-fee-token-codename-photon-e0927daf5c4c) to old fee token
- [ ] Inflation model vs ethereum's
- [ ] SDK Governance stuff (primarily parameter change proposals, upgrade proposals, community spend, etc).
- [ ] [`x/evm` module specification](https://github.com/ChainSafe/ethermint/tree/development/docs/spec/evm): see template [here](https://github.com/cosmos/cosmos-sdk/blob/master/docs/spec/SPEC-SPEC.md). 
- [ ] `AnteHandler` logic for `MsgEthereumTx`ADR: rationale
- [x] Ethermint Accounts (geth's secp256k1) and signing. Account not compatible with tendermint's `secp256k1`.
- [x] Address formats (`cosmos1...` vs `0x...`)
- [x] Encoding: ongoing migration to protobuf, compare with tendermint's Amino, and ethereum's RLP.
- [ ] Store: mention which DBs are currently supported by tendermint. Can link to SDK and Tendermint docs.
- [x] Client: currently though CLI and REST. Mention support for SDK's default rest-server and JSON-RPC.
- [ ] Light client: Tendermint light client vs Ethereum's.
- [x] Gas: compare Ethermint gas model against SDK's and ethereum's. 
- [ ] IBC compatibility
- [ ] Etheremint vs Ethereum 2.0 and other EVM-based PoS chains (Celo, etc). 
- [ ] Web3 dev tooling docs: ~Metamask~, Web3, ~Remix~, Truffle

**Comment by fedekunze** [comment]
@austinabell feel free to add any item that you think would be good to document 👍

**Comment by austinabell** [comment]
Documenting using evm as a module vs using Ethermint could be very useful! I have that outdated template https://github.com/austinabell/etherminty that could be updated as an example and put somewhere more accessible.

I think specific docs around converting an Ethereum address to a Cosmos one would be useful (specifically their formatting) as well as maybe some info about exporting and using their keys outside of Ethermint in dev tooling like Metamask. This has tripped up a few and making it clear that the Cosmos formatted address and the hex encoding format of the Ethereum address can represent the same underlying data/address.

**Comment by fedekunze** [comment]
thanks! Agree that we will def need dev tooling docs

**Comment by fedekunze** [comment]
@okwme any suggestions?

**Comment by okwme** [comment]
* yea the address conversion stuff would be really helpful! It's even confusing working with the same address on different evm chains since there's the potential for chain id to be used in the derivation path.
* it's a larger issue than just ethermint but some info on basic tasks involved in running a persistent node or a production node for a permissioned network could be valuable. Like I've been developing my contracts on a local ethermint instance and i'm ready to launch a semi-stable public testnet what should i think about when using 1) digital ocean 2) AWS 3) google etc. Stuff like settin gup nginx with reverse proxy or setting the node flag to use localhost versus 0.0.0.0 to make the port accessible to the wider internet. That stuff is all relevant to projects outside of Ethermint but would be good to either link to docs on that info or write up something minimal.
  * (it is also relevant to the change in paradigm when you become your own infura provider by running a service like this)\
* bridge documentation?
