### ISSUE TITLE
EVM tests

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ethermint#385]
# Summary

Implement table-tests for each of the following files and ensure close to 100% line coverage. 

> **NOTE**: The use of table tests is really important because it helps with readability and ensuring that all lines are covered from top to bottom. Existing tests that don't use table tests need to be refactored to use them.

In the case of state_object, state_transition, statedb, keeper and querier files and all files which use shared components, the use of a testing suite, with a `suite.Require()` testing context, is recommended. Otherwise, the `require` package can be used (eg: tests for genesis, msg, etc).

**`x/evm/types`:**

- [x] genesis_test.go
- [x] journal_test.go - #384 (@fedekunze)
- [x] logs_test.go
- [ ] msg_test.go - missing minor functions tests
- [x] state_object_test.go (@fedekunze)
- [x] state_transition_test.go (Justin)
- [x] statedb_test.go - Refactor to table tests (justin)
- [ ] tx_data_test.go - implement JSON and YAML marshaling + tests
- [ ] utils_test.go

**`x/evm/keeper`:**

- [ ] keeper_test.go (Justin)
- [ ] querier_test.go (Justin)
- [x] statedb_test.go (can have the same as `types/statedb_test.go`)(justin)

**`x/evm`:**

- [ ] abci_test.go (@fedekunze)
- [ ] genesis_test.go (@fedekunze)
- [ ] handler_test.go (@noot)

**`x/evm/types/statedb_test`:** (@fedekunze)
- [ ] GetCommittedState
- [ ] IntermediateRoot
- [ ] RevertToSnapshot
- [ ] ForEachStorage (important)

**Comment by fedekunze** [comment]
@araskachoi I didn't assign you because I know you are busy with benchmarks. Feel free to self-assign yourself if you want 👍
